name: Deploy via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: FTP Deploy para Locaweb
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "."  # Se todos os arquivos estiverem na raiz do repositório
          # localDir: "public"  # Se os arquivos estiverem em uma pasta chamada "public"
          remoteDir: "/home/onmicare1/"