name: Deploy Deno Application

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Deno Application
        run: deno run --allow-net --allow-read --allow-write main.ts
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: deno-app
          path: ./dist  # Ajuste o caminho para o diretório de saída do build