name: Deploy Deno Application

on:
  push:
    branches:
      - main  # O deploy ocorre quando há push na branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Faz o checkout do código
      - name: Build Deno Application
        run: deno run --allow-net --allow-read --allow-write main.ts  # Comando para rodar o build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: ./dist  # Diretório de saída do build
          name: deno-app  # Nome do artefato

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Deploy to FTP
        uses: locaweb/ftp-deploy@1.0.0  # Ação de deploy via FTP
        with:
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: './Onmicare'  # Diretório contendo os arquivos a serem enviados
          remoteDir: '/home/onmicare1/'  # Caminho remoto para enviar os arquivos
          options: '-r'  # Forçar recursão para enviar subdiretórios
