name: Deploy via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: FTP Deploy para Locaweb
        uses: ./ftp-deploy
        with:
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "."  # Se todos os arquivos estiverem na raiz do repositório
          remoteDir: "/home/onmicare1/public_html"  # Caminho correto no servidor FTP
          forceSsl: true  # Habilitar SSL, se necessário
