name: Deploy via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: FTP Deploy para Locaweb
        uses: ./ftp-deploy
        with:
          host: ftp://webftp.locaweb.com.br
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: ./
          remoteDir: /files/public_html
