name: Deploy via FTP

on:
  push:
    branches:
      - main # Substitua pela branch que você utiliza para deploy

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      # Faz o checkout do repositório
      - uses: actions/checkout@v2

      # Publica os arquivos no servidor FTP
      - name: FTP Deploy para Locaweb
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          localDir: "onmicare" # Substitua pelo diretório local do seu projeto
          remoteDir: "/home/onmicare1/public_html" # Caminho remoto baseado no diretório raiz
