name: Deploy via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: FTP Deploy para Locaweb
        uses: ./ftp-deploy
        with:
          INPUT_HOST: ${{ secrets.FTP_HOST }}
          INPUT_USER: ${{ secrets.FTP_USER }}
          INPUT_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          INPUT_LOCALDIR: "."  # Se todos os arquivos estiverem na raiz do repositório
          INPUT_REMOTEDIR: "/public_html"  # Caminho correto no servidor FTP
          INPUT_FORCESSL: "true"  # Habilitar SSL, se necessário
